export const useLoremIpsum = () =>
  useState(() => [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.",
    "Nullam varius, turpis et commodo pharetra, est eros bibendum elit, nec luctus magna felis sollicitudin mauris.",
    "Integer in mauris eu nibh euismod gravida. Duis ac tellus et risus vulputate vehicula.",
    "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum.",
    "Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus.",
    "Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "In rutrum. Etiam eu libero sed arcu vehicula ultricies a non tortor.",
    "Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus.",
    "Phasellus ultrices nulla quis nibh. Quisque a lectus.",
    "Morbi quis ante. Nullam cursus lacinia erat.",
    "Integer quam lacus, aliquet id, aliquet eu, euismod ut, mi.",
    "Fusce aliquet. Nulla eleifend, purus in laoreet varius, lectus libero hendrerit justo, id pulvinar quam augue ac quam.",
    "Sed lectus. Integer euismod lacus luctus magna.",
    "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam.",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui.",
    "Praesent blandit dolor. Sed non quam.",
    "In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet.",
    "Donec lacus nunc, viverra nec, blandit vel, egestas et, augue.",
    "Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim.",
    "Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper.",
    "Nulla facilisi. Integer lacinia sollicitudin massa.",
    "Cras metus. Sed aliquet risus a tortor.",
    "Integer id quam. Morbi mi.",
    "Quisque nisl felis, venenatis tristique, dignissim in, ultrices sit amet, augue.",
    "Proin sodales libero eget ante. Nulla quam.",
    "Aenean laoreet. Vestibulum nisi lectus, commodo ac, facilisis ac, ultricies eu, pede.",
    "Ut orci risus, accumsan porttitor, cursus quis, aliquet eget, justo.",
    "Curabitur dictum gravida mauris.",
    "Nam arcu libero, nonummy eget, consectetuer id, vulputate a, magna.",
    "Donec vehicula augue eu neque.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "Mauris ut leo. Cras viverra metus rhoncus sem.",
    "Nulla et lectus vestibulum urna fringilla ultrices.",
    "Phasellus eu tellus sit amet tortor gravida placerat.",
    "Integer sapien est, iaculis in, pretium quis, viverra ac, nunc.",
    "Praesent eget sem vel leo ultrices bibendum.",
    "Aenean faucibus. Morbi dolor nulla, malesuada eu, pulvinar at, mollis ac, nulla.",
    "Curabitur a felis in nunc fringilla tristique.",
    "Donec posuere vulputate arcu. Phasellus accumsan cursus velit.",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed aliquam, nisi quis porttitor congue.",
    "Praesent sapien massa, convallis a, varius quis, dignissim lacinia, nunc.",
    "Curabitur tortor. Pellentesque nibh. Aenean quam.",
    "In scelerisque sem at dolor.",
    "Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor.",
  ]);
